-- MySQL Script generated by MySQL Workbench
-- Fri Feb  2 00:20:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema back2learn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema back2learn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `back2learn` DEFAULT CHARACTER SET utf8mb4 ;
USE `back2learn` ;

-- -----------------------------------------------------
-- Table `back2learn`.`zone_supervision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back2learn`.`zone_supervision` (
  `idzone_supervision` INT(11) NOT NULL AUTO_INCREMENT,
  `ville` TEXT NULL DEFAULT NULL,
  `commune_quartier` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idzone_supervision`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `back2learn`.`administareur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back2learn`.`administareur` (
  `idgestionnaires` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL DEFAULT NULL,
  `prenom` TEXT NULL DEFAULT NULL,
  `date_Naissance` TEXT NULL DEFAULT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `contact` TEXT NULL DEFAULT NULL,
  `password` TEXT NULL DEFAULT NULL,
  `cni` TEXT NULL DEFAULT NULL,
  `ville` TEXT NULL DEFAULT NULL,
  `commune_quatier` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `zone_supervision_idzone` INT(11) NOT NULL,
  PRIMARY KEY (`idgestionnaires`, `zone_supervision_idzone`),
  INDEX `fk_administareur_zone_supervision1_idx` (`zone_supervision_idzone` ASC) ,
  CONSTRAINT `fk_administareur_zone_supervision1`
    FOREIGN KEY (`zone_supervision_idzone`)
    REFERENCES `back2learn`.`zone_supervision` (`idzone_supervision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `back2learn`.`factures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back2learn`.`factures` (
  `idfactures` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_fact` TEXT NULL DEFAULT NULL,
  `description_fact` TEXT NULL DEFAULT NULL,
  `niveau` VARCHAR(45) NULL DEFAULT NULL,
  `serie` VARCHAR(45) NULL DEFAULT NULL,
  `MontantFact` TEXT NULL DEFAULT NULL,
  `date_fact` DATE NULL DEFAULT NULL,
  `payement` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idfactures`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `back2learn`.`eleves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back2learn`.`eleves` (
  `ideleves` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL DEFAULT NULL,
  `prenom` TEXT NULL DEFAULT NULL,
  `date_naissance` TEXT NULL DEFAULT NULL,
  `Telephone` TEXT NULL DEFAULT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `password` TEXT NULL DEFAULT NULL,
  `niveau` TEXT NULL DEFAULT NULL,
  `serie` TEXT NULL DEFAULT NULL,
  `nom_parent` TEXT NULL DEFAULT NULL,
  `contact_parent` TEXT NULL DEFAULT NULL,
  `emploi_du_temps` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `administareur_idgestionnaires` INT(10) UNSIGNED NOT NULL,
  `factures_idfactures` INT(11) NOT NULL,
  PRIMARY KEY (`ideleves`, `administareur_idgestionnaires`, `factures_idfactures`),
  INDEX `fk_eleves_administareur1_idx` (`administareur_idgestionnaires` ASC) ,
  INDEX `fk_eleves_factures1_idx` (`factures_idfactures` ASC) ,
  CONSTRAINT `fk_eleves_administareur1`
    FOREIGN KEY (`administareur_idgestionnaires`)
    REFERENCES `back2learn`.`administareur` (`idgestionnaires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eleves_factures1`
    FOREIGN KEY (`factures_idfactures`)
    REFERENCES `back2learn`.`factures` (`idfactures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `back2learn`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back2learn`.`cours` (
  `idcours` INT(11) NOT NULL AUTO_INCREMENT,
  `type_cours` TEXT NULL DEFAULT NULL,
  `prix_cours` TEXT NULL DEFAULT NULL,
  `emploi_du_temps` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `eleves_ideleves` INT(11) NOT NULL,
  `administareur_idgestionnaires` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idcours`, `eleves_ideleves`, `administareur_idgestionnaires`),
  INDEX `fk_cours_eleves1_idx` (`eleves_ideleves` ASC) ,
  INDEX `fk_cours_administareur1_idx` (`administareur_idgestionnaires` ASC) ,
  CONSTRAINT `fk_cours_eleves1`
    FOREIGN KEY (`eleves_ideleves`)
    REFERENCES `back2learn`.`eleves` (`ideleves`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cours_administareur1`
    FOREIGN KEY (`administareur_idgestionnaires`)
    REFERENCES `back2learn`.`administareur` (`idgestionnaires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `back2learn`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back2learn`.`classes` (
  `idclasses` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL DEFAULT NULL,
  `Lieu` TEXT NULL DEFAULT NULL,
  `commune_quartier` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `cours_idcours` INT(11) NOT NULL,
  `administareur_idgestionnaires` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idclasses`, `cours_idcours`),
  INDEX `fk_classes_cours1_idx` (`cours_idcours` ASC) ,
  INDEX `fk_classes_administareur1_idx` (`administareur_idgestionnaires` ASC) ,
  CONSTRAINT `fk_classes_cours1`
    FOREIGN KEY (`cours_idcours`)
    REFERENCES `back2learn`.`cours` (`idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_administareur1`
    FOREIGN KEY (`administareur_idgestionnaires`)
    REFERENCES `back2learn`.`administareur` (`idgestionnaires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `back2learn`.`matiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back2learn`.`matiere` (
  `idmatiere` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_mat` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `cours_idcours` INT(11) NOT NULL,
  PRIMARY KEY (`idmatiere`, `cours_idcours`),
  INDEX `fk_matiere_cours1_idx` (`cours_idcours` ASC) ,
  CONSTRAINT `fk_matiere_cours1`
    FOREIGN KEY (`cours_idcours`)
    REFERENCES `back2learn`.`cours` (`idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `back2learn`.`encadreurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back2learn`.`encadreurs` (
  `idencadreurs` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL DEFAULT NULL,
  `prenom` TEXT NULL DEFAULT NULL,
  `date_naissance` TEXT NULL DEFAULT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `password` TEXT NULL DEFAULT NULL,
  `profession` TEXT NULL DEFAULT NULL,
  `diplome` TEXT NULL DEFAULT NULL,
  `cni` TEXT NULL DEFAULT NULL,
  `ville` TEXT NULL DEFAULT NULL,
  `encadreurscol` TEXT NULL DEFAULT NULL,
  `commune_quatier` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `matiere_idmatiere` INT(11) NOT NULL,
  `administareur_idgestionnaires` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idencadreurs`, `matiere_idmatiere`, `administareur_idgestionnaires`),
  INDEX `fk_encadreurs_matiere_idx` (`matiere_idmatiere` ASC) ,
  INDEX `fk_encadreurs_administareur1_idx` (`administareur_idgestionnaires` ASC) ,
  CONSTRAINT `fk_encadreurs_matiere`
    FOREIGN KEY (`matiere_idmatiere`)
    REFERENCES `back2learn`.`matiere` (`idmatiere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encadreurs_administareur1`
    FOREIGN KEY (`administareur_idgestionnaires`)
    REFERENCES `back2learn`.`administareur` (`idgestionnaires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
